### ISSUE TITLE
[Multiple Books] => Section Titles on Dev00 showing HTML

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#171]
# Scenario

Section titles in the WebView rendition of some of the TEA books are showing their HTML. Only appears in the section title of the page and in the tab text for the browser, not in the TOC navigation. May also occur in other books, but search is currently not cooperating. Will update issue with additional information as it becomes available.

This was previously resolved / seems to be a regression.

Books showing this error as of 2017-03-24T10:40
   * [HS Physics](https://dev00.cnx.org/contents/2_3FQXUs@2.3:LOc1OoJU@2/11Introduction)
   * [HS Statistics](https://dev00.cnx.org/contents/vtH503Ry@2.23:Ps9k1UFI@2/Introduction)
   * [AP Biology](https://dev00.cnx.org/contents/J89g5L2C@3.1:Prllm-7z@5/Introduction)
   * [AP Physics 2](https://dev00.cnx.org/contents/TbYCj4yh@1.37:hPuyTFoP@2/Connection-for-AP-Courses)

# Reproducibility Details

* **Impact area**: Content 
*  **User**: Not logged in.
*  **URL / Location**: 
Example: https://dev00.cnx.org/contents/2_3FQXUs@2.3:LOc1OoJU@2/11Introduction
*  **Steps to reproduce**:
   - Access content at dev00.cnx.org
   - Observe titles.

* **How many times were you able to reproduce the issue?**  3+
* **Images or screenshots Included:** Yes    (_attach below_)

# Environment:

* **Instance**: dev00
* **OS**: macOS
* **Browser**: Chrome
# Impact

* **Severity**: High 
* **Frequency of occurrence**: High

![image](https://cloud.githubusercontent.com/assets/12678235/24298113/0412fd3e-1073-11e7-95da-c5bcec4247ad.png)

**Comment by philschatz** [comment]
hmm, this looks like this might be a long-running issue in webview. The [JSON content](https://archive-dev00.cnx.org/contents/dbfdc541-752c-4a79-9e83-d32b1ca2c176@2.3:2ce7353a-8254-48d3-9294-cc959baf09a2@2.json) does not have escaped HTML which seems to indicate that webview is doing the HTML escaping

/cc @edwoodward @RoyEJohnson might be able to find/fix where in webview this is happening

**Comment by philschatz** [comment]
[Trello Story](https://trello.com/c/bIqKEK1W/15-cte-webview1-01-update-webview-design-to-ensure-usability)

**Comment by philschatz** [comment]
I believe this was addressed in https://github.com/Connexions/webview/pull/1532

**Comment by Stackblocks** [comment]
![image](https://cloud.githubusercontent.com/assets/12678235/26603885/0f0d6a52-454e-11e7-9dd0-fd3dd4413ba0.png)

Still seeing this in standard and composite module titles on dev00. Send me a message once the fix is on and i'll re-test and re-close.

**Comment by RoyEJohnson** [comment]
To insert HTML instead of plain text, it's a triple-mustache: `{{{htmlVariable}}}`.

**Comment by kerwinso** [comment]
List of affected books, each will be checked off when it passes QA:
- [ ]  Principles of Econ
- [ ]  Statistics
- [ ]  College Biology
- [ ]  AP Physics

@Stackblocks Any more? feel free to edit this list

**Comment by Stackblocks** [comment]
_Resolved on dev.cnx.org._

![image](https://user-images.githubusercontent.com/12678235/26936232-afe0f138-4c33-11e7-99a7-35f50a9d7da8.png)
![image](https://user-images.githubusercontent.com/12678235/26936234-b2347a7c-4c33-11e7-9485-26bdd95c8d0d.png)
