### ISSUE TITLE
Multiple Books => Key Terms not sorted alphabetically. 

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-recipes#179]
# Description
The Key Terms in the baked version  are not sorted in alphabetical order. While the example and screenshot linked are from Chapter 1 of Introductory Statistics, this is true throughout the books.

# Related Materials
- [Chapter 1 Key Terms](https://dev00.cnx.org/contents/MBiUQmmY@18.13:u8z6aR1b@11/Key-Terms) 

![image](https://cloud.githubusercontent.com/assets/12678235/25251253/51a221bc-25de-11e7-9ae9-6f3a8d3a69bb.png)

**Comment by kerwinso** [comment]
Also found in College Biology:
![image](https://cloud.githubusercontent.com/assets/11298165/26322878/6ae8b23a-3ef2-11e7-927a-04cace7e325c.png)

**Comment by Stackblocks** [comment]
Also still happening in Econ.
![image](https://cloud.githubusercontent.com/assets/12678235/26371263/d80c58a8-3fbf-11e7-9aee-dd422ba7490e.png)

**Comment by tomjw64** [comment]
The relevant baked glossaries appear with no issue with content grabbed from tea.cnx. Are these examples from dev.cnx? If so, this is almost definitely a content issue with dev.cnx.

# **Stats:**
![stats](https://cloud.githubusercontent.com/assets/1285308/26697908/572dc71e-46d9-11e7-9930-3ca6fafd5bbc.png)


# **Econ:**
![econ](https://cloud.githubusercontent.com/assets/1285308/26697914/5e11c3dc-46d9-11e7-82e7-9d5e0085f67d.png)

**Comment by Stackblocks** [comment]
Tests were performed on dev.cnx, so that full well may be the case.

**Comment by tomjw64** [comment]
I just pulled content from dev and still cannot reproduce the issue. I guess not instead of a content issue this is a ??? issue.

**Comment by tomjw64** [comment]
Never-mind, I found exactly what's happening with statistics.
![untitled](https://cloud.githubusercontent.com/assets/1285308/26701797/0bf664fe-46e8-11e7-99c7-32a42858e75c.png)

**Comment by tomjw64** [comment]
@Stackblocks does this still occur on a fresh fetched book? on latest easybake master version?

**Comment by kerwinso** [comment]
This is occurring in the Glossary sections of AP Physics, which was just baked yesterday:
https://dev.cnx.org/contents/jQSmhtXo@14.5:aAHggGU4@14.5/Glossary

![image](https://cloud.githubusercontent.com/assets/11298165/26731781/c66c084c-477a-11e7-898f-9fc3ec3d4356.png)

**Comment by kerwinso** [comment]
List of affected books, each will be checked off when it passes QA:
- [ ]  Principles of Econ
- [ ]  Statistics
- [ ]  College Biology
- [ ]  AP Physics

@Stackblocks Any more?

**Comment by Stackblocks** [comment]
As of 2017-06-06 this is still occurring on dev.cnx.org. [Here](https://dev.cnx.org/contents/MBiUQmmY@18.13:fBy6ipnF@18.13/Key-Terms) is an example of the key terms still being out of sorts even after a fresh bake.

**Comment by helenemccarron** [comment]
This doesn't appear locally, only on dev.cnx.org

**Comment by Stackblocks** [comment]
Also happening on tea.cnx.org for what that's worth.

![image](https://user-images.githubusercontent.com/12678235/27290472-f2b40eee-54d2-11e7-8504-5b1a44f86f7f.png)

**Comment by reedstrm** [comment]
@pumazi My most recent work on this (using https://dev.cnx.org/contents/MBiUQmmY@18.13:csNqFoaL@18.13/Key-Terms ) When baking via CLI, either on my local machine or on dev00, the order for that page is correct, both in the baked html and the baked epub generated from that. Somehow, when baked via the ansyc job, it ends up as you see, with two separate stretches of alphabetical order.

**Comment by pumazi** [comment]
Things I've looked into:
- ✅ local raw single html == dev raw single html
- ✅ local baked single html == dev baked single html
- ❌ manually baked from the shell (~7mins) with unalphabetized results

### Instructions for baking from the shell

Run `pshell /etc/cnx/publishing/app.ini` to open a python interpreter with the application loaded.

The following are steps I took to invoke the baking process:
```py
>>> from psycopg2.extensions import Notify
>>> notif = Notify(pid=0, channel='post_publication', payload='{"module_ident": 176678, "ident_hash": "30189442-6998-4686-ac05-ed152b91b9de@18.13", "timestamp": "<date>"}')
>>> from cnxpublishing.events import PostPublicationEvent
>>> event = PostPublicationEvent(notif)
>>> from cnxpublishing.subscribers import post_publication_processing
>>> post_publication_processing(event)

**Comment by pumazi** [comment]
What has recently changed? We know the wrapping process for invoking baking has changed. Has anything else changed?

**Comment by reedstrm** [comment]
Ah ha! It's namespaces. The html parsed in from files is parsed as non-namespaced html. The html derived from the model built from the database is namespaced xhtml. The sort-by selector is converted to an XPath that is failing to match the xhtml.

**Comment by reedstrm** [comment]
BTW, @pumazi using your pshell steps to get to a spot to use pdb was critical to finding this (along w/ a ssh tunnel to the dev database) I was then able to step through and verify where things diverged.

**Comment by reedstrm** [comment]
This is fixed by Connexions/cnx-epub#119

**Comment by philschatz** [comment]
I think the PR's that will need to be merged in order for this to be fixed are:

- https://github.com/Connexions/rhaptos.cnxmlutils/pull/158
- https://github.com/Connexions/cnx-easybake/pull/72
- https://github.com/Connexions/cnx-recipes/pull/274

**Comment by nyxer95** [comment]
Per @reedstrm -- All regressions between dev and QA probably got fixed with deploy on Monday and additional code changes that we deployed an hour ago.

**Comment by nyxer95** [comment]
Per @reedstrm -- All regressions between dev and QA probably got fixed with deploy on Monday and additional code changes that we deployed an hour ago.

**Comment by kerwinso** [comment]
This is still broken in University Physics (https://qa.cnx.org/contents/1Q9uMg_a@5.22:zYtuqjNf@5.22/Chapter-Review). I've rebaked a couple times now:

![image](https://user-images.githubusercontent.com/11298165/28434778-48bb1490-6d56-11e7-9e26-6ba67cbd9be0.png)

NOTE: it may not be an issue for other books. So far I've rebaked Biology and it looks OK: 
https://qa.cnx.org/contents/GFy_h8cu@10.115:i3hNH4S2@10.115/Key-Terms

**Comment by philschatz** [comment]
@tomjw64 Can you take a look at this? I took a look and it seems it might be a selector problem. U-Physics uses compound-composite pages for the Key Terms while other books like Biology use just a Composite Page. 

Helene said she was going to take a look at this but then went on Vacation. That is probably how this Issue fell through the cracks.

**Comment by tomjw64** [comment]
Fix for u-physics is in PR #299

**Comment by kerwinso** [comment]
Verified on https://qa.cnx.org/contents/1Q9uMg_a@5.24:c7wUoohX@5.24/Chapter-Review after rebaking on `u-physics-glossary-sort` (#299).

![image](https://user-images.githubusercontent.com/11298165/28882276-693833e6-7770-11e7-8727-606dbe2970c4.png)
