### ISSUE TITLE
Multiple books => Footnote numbering not continuous throughout chapter

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#225]
May affect multiple books @Stackblocks. We'd agreed that footnotes should be continuously numbered throughout the chapter. This is not happening in Biology.

In Chapter 9, there are 2 separate modules that each have one footnote: 9.1 and 9.4. The footnote in 9.4 (`G. Manning` et al.) should be numbered `2` in the webview (like it is in the PDF), but it is numbered `1`. 

Webview URL (9.4): https://dev00.cnx.org/contents/GFy_h8cu@10.61:Gj6xeWoG@7/94-Signaling-in-Single-Celled-

![image](https://cloud.githubusercontent.com/assets/11298165/26501574/9e6cc51e-41ff-11e7-8c28-952f27012ae3.png)

![image](https://cloud.githubusercontent.com/assets/11298165/26501562/9b251a96-41ff-11e7-8265-68d2071bf28c.png)

**Comment by kerwinso** [comment]
Also found in Chp. 19.1 and 19.2.

**Comment by nyxer95** [comment]
I agree with Kerwin and Alan. Footnotes should be numbered continuously throughout the chapter.

**Comment by tomjw64** [comment]
Resolved in PR #229

**Comment by kerwinso** [comment]
Still an issue in AP Physics:
https://dev.cnx.org/contents/jQSmhtXo@14.5:KcbI9HWl@2/78-Work-Energy-and-Power-in-Hu

![image](https://cloud.githubusercontent.com/assets/11298165/26744159/6aa8ddd4-47aa-11e7-8f6f-4079c69f4e80.png)

**Comment by kerwinso** [comment]
List of affected books, each will be checked off when it passes QA:

- [ ]  College Biology
- [ ]  AP Physics

**Comment by kerwinso** [comment]
@tomjw64 @helenemccarron This is still an issue for College Biology on dev: 
https://dev.cnx.org/contents/GFy_h8cu@10.61:Gj6xeWoG@7/94-Signaling-in-Single-Celled-#footnote-ref1
Also: clicking on the footnote number jumps to the top of the page, not the reference. This is probably a webview issue, but it does work OK on prod (cnx.org).

**Comment by kerwinso** [comment]
Verified fix for [College Biology](https://dev.cnx.org/contents/185cbf87-c72e-48f5-b51e-f14f21b5eabd) on `bio-fixes` branch.

![image](https://user-images.githubusercontent.com/11298165/26838204-174aaec6-4aa5-11e7-86ec-665436119cd0.png)

![image](https://user-images.githubusercontent.com/11298165/26838209-19bdbdce-4aa5-11e7-8fe3-654c0eacbfec.png)

![image](https://user-images.githubusercontent.com/11298165/26838213-1cf332f8-4aa5-11e7-8545-7ade002ca323.png)

**Comment by kerwinso** [comment]
Also verified fix for [AP Physics](https://dev.cnx.org/contents/jQSmhtXo@14.5:KcbI9HWl@2/78-Work-Energy-and-Power-in-Hu) with `bio-fixes` ruleset.

![image](https://user-images.githubusercontent.com/11298165/26841343-d6775692-4aae-11e7-849b-0f884b7bf262.png)
