### ISSUE TITLE
University Physics => Equation numbering does not match PDF

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#275]
There are numerous instances where equations that should be numbered in the webview are not, thus throwing off equation numbering for the entire chapter compared to the PDF.

My understanding is that only equations marked up as `<equation class="unnumbered">` should not be numbered. I have not been able to find a pattern in the equations that are being skipped with numbering -- some are inside a note class, many are not.

Here are some examples, I'm sure there are more. All screenshots are taken from dev.cnx.org in Chrome (but reproducible in other browsers).

_Webview on the left, PDF on the right_
Chp. 2.1:
![image](https://user-images.githubusercontent.com/11298165/27646459-44494b1c-5bee-11e7-94e3-590233bbdafc.png)

Chp. 2.4 (an instance where an equation inside a note _and_ an equation outside of a note are both skipped):
![image](https://user-images.githubusercontent.com/11298165/27653306-5502eb14-5c04-11e7-8a9c-5a21e3bec031.png)

Chp. 3.1:
![image](https://user-images.githubusercontent.com/11298165/27646286-dd98f174-5bed-11e7-9849-ab5494cbaf5a.png)

Chp. 4.1:
![image](https://user-images.githubusercontent.com/11298165/27646433-37b3759e-5bee-11e7-912c-6b2b8730a660.png)

**Comment by tomjw64** [comment]
Addressed in PR #280

**Comment by kerwinso** [comment]
OK this is weird... on qa.cnx.org, most of the equations look fine EXCEPT for the last 2 modules of chapter 15 ('Damped Oscillations' and 'Forced Oscillations'). Those 2 modules do not number any equations, although the other modules in the chapter do, as does chapter 16.

@tomjw64 Should I just try baking again?

![image](https://user-images.githubusercontent.com/11298165/27932422-5316c4a0-6263-11e7-8778-dd0761731567.png)

![image](https://user-images.githubusercontent.com/11298165/27932426-5673ce18-6263-11e7-9fe6-0037702742a2.png)

**Comment by kerwinso** [comment]
@tomjw64 Tried rebaking several times and still seeing this issue. Specifically: random modules in Chapter 15 (screenshots [above](https://github.com/Connexions/cnx-recipes/issues/275#issuecomment-313516803)) and Chapter 17 (screenshot below) in [University Physics volume 1](https://qa.cnx.org/contents/1Q9uMg_a@5.22:B3zy4pYl@4/172-Sound-Waves) are missing equation numbers.

![image](https://user-images.githubusercontent.com/11298165/27965570-dbed63f8-6301-11e7-99b3-045ffa51925e.png)

**Comment by kerwinso** [comment]
addressed again in #289

**Comment by kerwinso** [comment]
Verified equation numbering fix on qa.cnx.org for all instances above plus several entire chapters:

![image](https://user-images.githubusercontent.com/11298165/28174670-bd02c446-67b7-11e7-880a-84eab052344d.png)


(Don't worry about equation number styling in the screenshot such as the number being on a different line -- that was addressed with https://github.com/Connexions/webview/pull/1570 which was merged. I'm testing various non-`master` sha's on webview right now, which is why the styling looks off. The numbering is correct.)
