### ISSUE TITLE
Multiple books => Appendix title missing letter and pipe

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-recipes#285]
Regression: re-baked books on qa.cnx.org no longer have the correct appendix titles (missing letter and pipe).

Here's what [University Physics](https://qa.cnx.org/contents/1Q9uMg_a@5.22:7P5bvslo@4/Fundamental-Constants) looks like on qa.cnx.org:
![image](https://user-images.githubusercontent.com/11298165/27918740-77a8457e-6235-11e7-80fa-440939153101.png)

Here's what it should look like:
![image](https://user-images.githubusercontent.com/11298165/27918756-7f9b2d8c-6235-11e7-9b32-7af19bbc4209.png)

**Comment by kerwinso** [comment]
Originally fixed with #261 for #260.

**Comment by nyxer95** [comment]
This requires cnxml to html transform and require re-baking.

**Comment by nyxer95** [comment]
Per @reedstrm -- All regressions between dev and QA probably got fixed with deploy on Monday and additional code changes that we deployed an hour ago.

**Comment by kerwinso** [comment]
Still an issue with University Physics. https://qa.cnx.org/contents/1Q9uMg_a@5.22:Kglg_o39@5/Units

![image](https://user-images.githubusercontent.com/11298165/28435244-d5882ec0-6d57-11e7-8736-d953d7c56a76.png)

NOTE: it may not be an issue for other books. So far I've rebaked Biology and it looks OK:
https://qa.cnx.org/contents/GFy_h8cu@10.115:hYdhUM0j@6/A--The-Periodic-Table-of-Eleme

**Comment by kerwinso** [comment]
@tomjw64 Can you please take a look while Helene is out?

**Comment by tomjw64** [comment]
Fresh download of u-physics from dev and baking from the tip of master does not reproduce this issue. My guess is that the content on QA is old. I will confirm.

**Comment by tomjw64** [comment]
Update: I've confirmed the content on QA is out of date. Preface/Appendices are missing their respective classes.

**Comment by tomjw64** [comment]
Larissa has made the necessary content fix on production.

**Comment by kerwinso** [comment]
Still trying to test this. On 7/28/17, I attempted to edit and re-publish the appendix modules in col12031, the University Physics vol. 1 collection on legacy-qa.cnx.org. 

For some reason this caused the front end collection to be taken down: https://github.com/Connexions/cnx-archive/issues/507

And, publishing currently appears to be hosed: https://github.com/Connexions/cnx-archive/issues/508

Karen is looking into both issues.

**Comment by kerwinso** [comment]
Karen manually updated this book in the `trees` table using SQL, so that the TOC points to the latest version of the appendices.

The result of that manual update is that I can now verify Thomas' assertion for this particular bug. Rebaking the University Physics vol. 1 collection with the appendix content now containing `class="appendix"` causes the letter and pipe to display properly.

https://qa.cnx.org/contents/1Q9uMg_a@5.24:ogTcCZzy@6/F--Chemistry

![image](https://user-images.githubusercontent.com/11298165/28884937-88271854-7779-11e7-96ec-c7cf177793ad.png)

So, this bug can now be closed. But publishing is still messed up and being investigated by Karen. Please refer to [the comment above](https://github.com/Connexions/cnx-recipes/issues/285#issuecomment-319716252) for links to the related issues.
