### ISSUE TITLE
Intro to Business: Exhibit displayed as Figure in paragraph

### ISSUE THREAD

**Issue by clteam18** [Connexions/cnx-recipes#449]
Global for all Chapters

https://content02.cnx.org/contents/-3P-qhDI@16.1:kouPko7R@5/12-Understanding-the-Business-

![image](https://user-images.githubusercontent.com/39794953/42385483-8962748e-815a-11e8-904e-999f3930e50f.png)

Figure callouts in paragraphs displayed as **Figure** instead of **Exhibit**

**Comment by openstaxalina** [comment]
For Monday: Larissa should review for priority.  I do not think this is a content issue.

**Comment by lwtchu** [comment]
Should be high priority. Numbering in text should match numbering for exhibit/figure.

**Comment by helenemccarron** [comment]
addressed in PR #469

**Comment by Stackblocks** [comment]
Still seeing `Figure #.#` instead of `Exhibit #.#` with new code. Re-assigning.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4a103397-947f-4975-ba4d-513df77405e5)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/37a41f2e-0499-4f5a-8103-670f256b5f21)
